/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShipmentTrack {
        "background": string;
        "color": string;
        "errorcolor": string;
        "errormessage": string;
    }
}
declare global {
    interface HTMLShipmentTrackElement extends Components.ShipmentTrack, HTMLStencilElement {
    }
    var HTMLShipmentTrackElement: {
        prototype: HTMLShipmentTrackElement;
        new (): HTMLShipmentTrackElement;
    };
    interface HTMLElementTagNameMap {
        "shipment-track": HTMLShipmentTrackElement;
    }
}
declare namespace LocalJSX {
    interface ShipmentTrack {
        "background"?: string;
        "color"?: string;
        "errorcolor"?: string;
        "errormessage"?: string;
    }
    interface IntrinsicElements {
        "shipment-track": ShipmentTrack;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shipment-track": LocalJSX.ShipmentTrack & JSXBase.HTMLAttributes<HTMLShipmentTrackElement>;
        }
    }
}
